# Generated by Django 3.2 on 2021-04-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_sensor', '0002_auto_20210417_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_sensor.device')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_sensor.sensor')),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
    ]
