# Generated by Django 3.2 on 2021-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_sensor', '0003_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[(1, 'TEMPERATURE SENSOR'), (2, 'PRESSURE SENSOR')], default=None, max_length=50, null=True),
        ),
    ]
